apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot2b-sep26-3e-app
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/chatbot2b-sep26-3e/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/chatbot2b-sep26-3e-gitops.git
    targetRevision: main
  destination:
    namespace: chatbot2b-sep26-3e
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
