kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chatbot2b-sep26-3e-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: chatbot2b-sep26-3e-dsp-job
    namespace: chatbot2b-sep26-3e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chatbot2b-sep26-3e-dsp-job-role