apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chatbot2b-sep26-3e
  janus-idp.io/tekton: chatbot2b-sep26-3e
  backstage.io/kubernetes-id: chatbot2b-sep26-3e
  backstage.io/kubernetes-namespace: chatbot2b-sep26-3e 
  app.kubernetes.io/part-of: chatbot2b-sep26-3e
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
