apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot2b-sep26-3e-model-config
data:
  MODEL_ENDPOINT: "http://ollama-route-ollama.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com"
  MODEL_NAME: "llama2:13b"