apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: chatbot2b-sep26-3e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot2b-sep26-3e 
  name: chatbot2b-sep26-3e
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: chatbot2b-sep26-3e 
    weight: 100 
  wildcardPolicy: None
